### ISSUE TITLE
Predecir la siguiente época de rebajas.

### ISSUE THREAD

**Issue by Paszser** [Paszser/ComparerApp#23]
Como programador voy a requerir de una función que a partir de datos de ciertas fechas clave aproximadas, me devuelva una predicción de las fechas variables del próximo año. El valor deberá tener sentido, ergo, estará para las fechas pre-verano entre Abril y Mayo, y para post-verano, entre Septiembre y Octubre.
Avanza la HU #4

**Comment by JJ** [comment]
No entiendo muy bien esto. "A partir de fechas clave" ¿qué significa? Significa que tienes que dar en cada predicción las fechas clave? ¿No sería más lógico que la tienda almacenara las fechas clave y la predicción sólo predijera la próxima fecha de rebaja?
Estás metiendo todo slos datos en la función, con lo que la tienda, que sólo tiene el nombre, en realidad no hace nada.
