### ISSUE TITLE
Uso y automatización de contenedor para el despliegue.

### ISSUE THREAD

**Issue by Paszser** [Paszser/ComparerApp#25]
Como programador, precisaré para el despliegue de nuestra aplicación un contenedor con las especificaciones pertinentes para que se lleva acabo el lanzamiento del código, tests, etc... Así como su automatización de actualizaciones con Docker Hub.

**Comment by JJ** [comment]
Tampoco plantea ningún problema, ni las restricciones que podría tener ese problema (que podrían convertirse en requisitos para el contenedor base)
