### ISSUE TITLE
Entidad Cliente

### ISSUE THREAD

**Issue by alexespana** [Paszser/ComparerApp#9]
Como programador, propongo que se cree una clase cliente que modelice toda la información de los clientes para resolver el problema referido en la [HU1] #3. Dicha clase tendrá atributos como:
* nombre
* fecha de nacimiento
* fecha de registro
* generos gustados
* lista de videojuegos comprados
* lista de videojuegos deseados

(En la descripción del user journey se habla de que el usuario tiene que hacer un breve registro al entrar en la aplicación, dicha información debe almacenarse en un producto valor. La lista de videojuegos deseados es la lista propia del usuario que se menciona.)

**Comment by JJ** [comment]
¿para qué sirve la fecha de nacimiento? ¿En qué ayuda a la lógica de negocio?
